import {defineComponent, reactive} from 'vue'
import dragon1 from '../../assets/home/dragon1.png';
import dragon2 from '../../assets/home/dragon2.png';
import dragon3 from '../../assets/home/dragon3.png';
import dragon4 from '../../assets/home/dragon4.png';
import dragon5 from '../../assets/home/dragon5.png';

export default defineComponent({
    name:'collectionMain',
    setup(){
        const state = reactive({
            text:'Welcome to the mainland of Blessland',
            desText:'Where there are 8888 completely different "reborn dragon" generated by algorithm. At present, the above line Ethereum blockchain. Get a "reborn dragon" that belongs to you and participate in the dragon race hegemony in this different world!',
            imgList:[{id:'d1',src:dragon1},{id:'d2',src:dragon2},{id:'d3',src:dragon3},{id:'d4',src:dragon4},{id:'d5',src:dragon5}]
        })
        return ()=>(
            <div id="collection" class="collection-mainbox">
                <div class="main-content">
                    <div class="top-title">
                        <h2 class="titleh2">{state.text}</h2>
                        <button class="morebtn">Show More</button>
                    </div>
                    <p class="desbox">{state.desText}</p>
                    <div class="imgbox">
                        {state.imgList.map((item)=>(<img src={item.src} key={item.id} class="imgitem" />))}
                    </div>
                    <div class="splitborder"></div>
                </div>
            </div>
        )
    }
})